name: Build and test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build binary
        run: env GOOS=linux GOARCH=amd64 go build -buildvcs=false -o ./out/server ./cmd/server/main.go

      - name: Run tests
        run: go test ./...
